### ISSUE TITLE
Technology file?

### ISSUE THREAD

**Issue by DrM00G** [eoriont/space-empires#10]
I think this does what mine and others economic classes do. Idk if this will be a problem with compatability... But wouldn't having it in the economic class just make more sense?

**Comment by eoriont** [comment]
You're right, it is part of the economic part of the game. The only reason I have it as its own file, is because I'm taking advantage of the OOP paradigm we are using. I made technology a class, so that I can store each type of technology, and dynamically get other data like prices, movement spaces, and the next level, all at the same time. 

I didn't want to put it in my economic phase file because it's already pretty bloated, and the technology class is just a bunch of (almost) independent functions.
