### ISSUE TITLE
Weird file in strategies

### ISSUE THREAD

**Issue by RileyPaddock** [eoriont/space-empires#6]
You have a file called strategy.py that is practically empty. It says it is for documentation purposes only but I don't understand what that means. You could probably get rid of this file but if I am missing something just let me know.

**Comment by eoriont** [comment]
That file is actually for describing what you should put in a strategy, when you need to make one. I just updated my repo to have a more full documentation in 1f6061b.

Pretty much, if some random person is interested in my game, and wants to make their own strategy, it would be easier for them to read this strategy file than to weed through my game code in order to make their own. Plus, if I ever forget the formats for the returns of certain functions, I can just reference this file and it's right there looking at me!
